CREATE TABLE USUARIO(
id_usuario SERIAL,
usuario VARCHAR(50),
email VARCHAR(150),
contrasenia VARCHAR(255),
nombre VARCHAR(50),
apellido VARCHAR(50),
fecha_nacimiento VARCHAR(50),
CONSTRAINT PK_USUARIO PRIMARY KEY (id_usuario),
CONSTRAINT UQ_USUARIO UNIQUE (usuario),
CONSTRAINT CK_USUARIO CHECK (usuario IS NOT NULL),
CONSTRAINT UQ_EMAIL UNIQUE (email),
CONSTRAINT CK_EMAIL CHECK (email IS NOT NULL),
CONSTRAINT CK_CONTRASENIA CHECK (contrasenia IS NOT NULL),
CONSTRAINT NN_NOMBRE CHECK (nombre IS NOT NULL),
CONSTRAINT CK_APELLIDO CHECK (apellido IS NOT NULL),
CONSTRAINT CK_FECHA_NACIMIENTO CHECK (fecha_nacimiento IS NOT NULL)
CONSTRAINT CK_FECHA_NACIMIENTO_VALIDA CHECK (fecha_nacimiento >= '1900-01-01')
);

CREATE TABLE VIDEO(
id_video SERIAL,
URL_video TEXT,
CONSTRAINT PK_VIDEO PRIMARY KEY (id_video),
CONSTRAINT CK_URL_VIDEO CHECK (URL_video IS NOT NULL)
);

CREATE TABLE CATEGORIA(
id_categoria SERIAL,
nombre_categoria VARCHAR(50),
CONSTRAINT PK_CATEGORIA PRIMARY KEY (id_categoria),
CONSTRAINT CK_NOMBRE_CATEGORIA CHECK (nombre_categoria IS NOT NULL)
);

CREATE TABLE CONTENIDO_CATEGORIA(
id_contenido INT,
id_categoria INT,
CONSTRAINT FK_CONTENIDO FOREIGN KEY (id_contenido) REFERENCES CONTENIDO(id_contenido),
CONSTRAINT FK_CATEGORIA FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)
);

CREATE TABLE CONTENIDO(
id_contenido SERIAL,
titulo VARCHAR(50),
descripcion TEXT,
fecha_publicacion DATE,
URL_miniatura TEXT,
id_video INT,
id_categoria INT,
CONSTRAINT PK_CONTENIDO PRIMARY KEY (id_contenido),
CONSTRAINT CK_TITULO CHECK (titulo IS NOT NULL),
CONSTRAINT CK_DESCRIPCION CHECK (descripcion IS NOT NULL),
CONSTRAINT CK_FECHA_PUBLICACION CHECK (fecha_publicacion IS NOT NULL),
CONSTRAINT CK_URL_MINIATURA CHECK (URL_miniatura IS NOT NULL),
CONSTRAINT FK_VIDEO FOREIGN KEY (id_video) REFERENCES VIDEO(id_video),
CONSTRAINT FK_CATEGORIA FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)
);

CREATE TABLE GUARDAR(
id_guardar SERIAL,
isFavorite BOOLEAN DEFAULT FALSE,
puntuacion INT,
id_contenido INT,
id_usuario INT,
CONSTRAINT PK_GUARDAR PRIMARY KEY (id_guardar),
CONSTRAINT CK_ISFAVORITE CHECK (isFavorite IS NOT NULL),
CONSTRAINT CK_PUNTUACION CHECK (puntuacion IS NOT NULL),
CONSTRAINT FK_CONTENIDO FOREIGN KEY (id_contenido) REFERENCES CONTENIDO(id_contenido),
CONSTRAINT FK_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);